/**
 * BOQA Cloudflare Worker — Static dashboard + API proxy + DEMO MODE
 *
 * Modes:
 *  - PRODUCTION: BOQA_BACKEND_URL is set → all /api/* and /ws requests are
 *    proxied to the Node.js backend (Northflank, Render, etc.)
 *  - DEMO: BOQA_BACKEND_URL is unset → the Worker itself validates X-API-Key
 *    against BOQA_API_KEY (default "BOQA123") and returns mock data so the
 *    dashboard is fully browsable without a backend.
 *
 * Architecture: User → Cloudflare Worker → (BOQA backend OR demo data)
 */

// ─── Demo data (used when BOQA_BACKEND_URL is unset) ────────────────────

const DEMO_API_KEY = 'BOQA123';

const DEMO_BUGS = [
  {
    id: 'BUG-2026-001',
    title: 'WebSocket authentication missing on /ws endpoint',
    severity: 'HIGH',
    category: 'Authentication',
    evidence_count: 4,
    confidence: 0.92,
    discovered_at: '2026-07-09T22:14:00Z',
    target: 'https://example.com',
  },
  {
    id: 'BUG-2026-002',
    title: 'CSRF token missing on POST /api/settings',
    severity: 'MEDIUM',
    category: 'CSRF',
    evidence_count: 3,
    confidence: 0.85,
    discovered_at: '2026-07-09T22:31:00Z',
    target: 'https://example.com',
  },
  {
    id: 'BUG-2026-003',
    title: 'Session cookie set without HttpOnly flag',
    severity: 'LOW',
    category: 'Cookie Security',
    evidence_count: 2,
    confidence: 0.98,
    discovered_at: '2026-07-09T22:48:00Z',
    target: 'https://example.com',
  },
];

const DEMO_COVERAGE = {
  overall_score: 67,
  endpoints_discovered: 42,
  endpoints_tested: 28,
  endpoints_untested: 14,
  coverage_by_category: {
    auth: 0.82,
    sessions: 0.71,
    csrf: 0.45,
    input_validation: 0.62,
    business_logic: 0.55,
  },
};

const DEMO_FINDINGS = {
  total: 7,
  findings: DEMO_BUGS.map((b) => ({
    id: b.id.replace('BUG', 'FND'),
    bug_id: b.id,
    title: b.title,
    severity: b.severity,
    confidence: b.confidence,
  })),
};

const DEMO_VERIFICATION_QUEUE = {
  total: 4,
  pending: 2,
  in_progress: 1,
  completed: 1,
  queue: [
    { id: 'VQ-001', bug_id: 'BUG-2026-001', status: 'in_progress', started_at: '2026-07-09T22:50:00Z' },
    { id: 'VQ-002', bug_id: 'BUG-2026-002', status: 'pending', started_at: null },
  ],
};

const DEMO_HEALTH = {
  status: 'ok',
  version: '1.4.0',
  modules_loaded: 67,
  agent_active: true,
  uptime_seconds: 1843,
};

// Markdown report for demo bug
function demoMarkdownReport(bugId) {
  const bug = DEMO_BUGS.find((b) => b.id === bugId);
  if (!bug) return `# Bug ${bugId} not found\n\nNo bug with that ID was found in the demo dataset.`;
  return `# Bug Bounty Report — ${bug.id}

## Summary

**Title:** ${bug.title}
**Severity:** ${bug.severity}
**Category:** ${bug.category}
**Confidence:** ${(bug.confidence * 100).toFixed(0)}%
**Discovered:** ${bug.discovered_at}
**Target:** ${bug.target}

## Description

During automated observation of ${bug.target}, the BOQA Hunter agent detected
a potential vulnerability in the ${bug.category.toLowerCase()} domain. The
finding was confirmed via ${bug.evidence_count} independent verification
artefacts, including network captures, DOM state snapshots, and replay
sessions.

## Reproduction

1. Navigate to ${bug.target}
2. Trigger the affected workflow
3. Observe the vulnerable response

## Evidence Chain

- Network capture (HAR): \`evidence-${bug.id}-network.har\`
- DOM snapshot: \`evidence-${bug.id}-dom.html\`
- Replay manifest: \`evidence-${bug.id}-manifest.json\`
- Verification result: \`evidence-${bug.id}-verify.json\`

## Impact

Successful exploitation could allow an attacker to bypass ${bug.category.toLowerCase()}
controls, potentially leading to unauthorized access or data exposure.

## Recommendation

Implement proper ${bug.category.toLowerCase()} controls as per OWASP best practices.

## Disclosure Timeline

- ${bug.discovered_at}: Vulnerability discovered by BOQA Hunter agent
- 2026-07-10T01:00:00Z: Evidence package compiled and verified
- 2026-07-10T01:30:00Z: Report prepared for disclosure

---
*Generated by BOQA v1.4.0 — Autonomous Decision Kernel*
`;
}

// JSON evidence package for demo bug
function demoJsonEvidence(bugId) {
  const bug = DEMO_BUGS.find((b) => b.id === bugId);
  if (!bug) return { error: 'not_found', bug_id: bugId };
  return {
    bug_id: bug.id,
    title: bug.title,
    severity: bug.severity,
    category: bug.category,
    confidence: bug.confidence,
    evidence_chain: [
      { type: 'network_capture', hash: 'sha256:abc123...', captured_at: bug.discovered_at },
      { type: 'dom_snapshot', hash: 'sha256:def456...', captured_at: bug.discovered_at },
      { type: 'replay_manifest', hash: 'sha256:ghi789...', captured_at: bug.discovered_at },
      { type: 'verification_result', hash: 'sha256:jkl012...', captured_at: bug.discovered_at },
    ],
    target: bug.target,
    discovered_at: bug.discovered_at,
    generated_by: 'BOQA v1.4.0',
  };
}

// ─── Auth check (demo mode) ─────────────────────────────────────────────

function isAuthorized(request, env) {
  const expectedKey = (env && env.BOQA_API_KEY) || DEMO_API_KEY;
  const provided = request.headers.get('X-API-Key') || new URL(request.url).searchParams.get('api_key');
  return provided === expectedKey;
}

function unauthorizedResponse() {
  return new Response(
    JSON.stringify({
      error: 'unauthorized',
      message: 'Valid API key required. Set X-API-Key header or api_key query param.',
    }),
    {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    }
  );
}

// ─── Demo mode handler ──────────────────────────────────────────────────

function handleDemoApi(request, env) {
  const url = new URL(request.url);

  if (!isAuthorized(request, env)) {
    return unauthorizedResponse();
  }

  // /api/bugs
  if (url.pathname === '/api/bugs') {
    return new Response(
      JSON.stringify({
        total: DEMO_BUGS.length,
        bugs: DEMO_BUGS,
        summary: {
          plans_created: 3,
          plans_executed: 3,
          bugs_confirmed: 3,
          false_positive_rejected: 1,
          findings_to_bug_ratio: '0.43',
          bugs_by_severity: { critical: 0, high: 1, medium: 1, low: 1 },
          bugs_by_category: { Authentication: 1, CSRF: 1, 'Cookie Security': 1 },
          average_confidence: 0.92,
        },
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  // /api/coverage
  if (url.pathname === '/api/coverage') {
    return new Response(JSON.stringify(DEMO_COVERAGE), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // /api/findings
  if (url.pathname === '/api/findings') {
    return new Response(JSON.stringify(DEMO_FINDINGS), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // /api/verification-queue
  if (url.pathname === '/api/verification-queue') {
    return new Response(JSON.stringify(DEMO_VERIFICATION_QUEUE), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // /api/health (whitelisted but include auth check anyway for consistency)
  if (url.pathname === '/api/health' || url.pathname === '/health') {
    return new Response(JSON.stringify(DEMO_HEALTH), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // /api/disclosures/:bugId/report — Markdown report download
  const disclosureMatch = url.pathname.match(/^\/api\/disclosures\/([^/]+)\/report$/);
  if (disclosureMatch) {
    const bugId = disclosureMatch[1];
    const markdown = demoMarkdownReport(bugId);
    return new Response(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="reporte-${bugId}.md"`,
      },
    });
  }

  // /api/bug/:bugId — JSON evidence package download
  const bugMatch = url.pathname.match(/^\/api\/bug\/([^/]+)$/);
  if (bugMatch) {
    const bugId = bugMatch[1];
    return new Response(JSON.stringify(demoJsonEvidence(bugId), null, 2), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="evidencia-${bugId}.json"`,
      },
    });
  }

  // Any other /api/* endpoint — return an empty-but-valid response
  return new Response(
    JSON.stringify({
      ok: true,
      demo_mode: true,
      message: 'This endpoint is not implemented in demo mode. Deploy the BOQA Node.js backend for full functionality.',
      path: url.pathname,
    }),
    {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    }
  );
}

// ─── Production mode handler (proxy to backend) ─────────────────────────

async function proxyToBackend(request, env) {
  const backendUrl = env.BOQA_BACKEND_URL;
  const url = new URL(request.url);
  const targetUrl = backendUrl.replace(/\/$/, '') + url.pathname + url.search;

  const proxyHeaders = new Headers(request.headers);
  try {
    proxyHeaders.set('Host', new URL(backendUrl).host);
  } catch (_) {
    return new Response(
      JSON.stringify({ error: 'invalid_backend_url', message: `BOQA_BACKEND_URL is invalid: ${backendUrl}` }),
      { status: 502, headers: { 'Content-Type': 'application/json' } }
    );
  }

  const proxyReq = new Request(targetUrl, {
    method: request.method,
    headers: proxyHeaders,
    body: request.method !== 'GET' && request.method !== 'HEAD' ? request.body : undefined,
    redirect: 'manual',
  });

  try {
    const backendRes = await fetch(proxyReq);
    const respHeaders = new Headers(backendRes.headers);
    respHeaders.delete('Transfer-Encoding');
    return new Response(backendRes.body, {
      status: backendRes.status,
      statusText: backendRes.statusText,
      headers: respHeaders,
    });
  } catch (err) {
    return new Response(
      JSON.stringify({
        error: 'backend_unreachable',
        message: `Could not reach BOQA backend at ${backendUrl}. ${err.message || ''}`,
      }),
      { status: 504, headers: { 'Content-Type': 'application/json' } }
    );
  }
}

// ─── Main Worker entry ──────────────────────────────────────────────────

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const backendConfigured = !!(env && env.BOQA_BACKEND_URL);

    // /api/* → demo mode OR proxy
    if (url.pathname.startsWith('/api/')) {
      if (backendConfigured) {
        return proxyToBackend(request, env);
      }
      return handleDemoApi(request, env);
    }

    // /ws → only meaningful in production mode (Worker can proxy WS upgrade)
    if (url.pathname === '/ws') {
      if (backendConfigured) {
        return proxyToBackend(request, env);
      }
      // Demo mode: WS not supported, return 426 Upgrade Required
      return new Response(
        JSON.stringify({
          error: 'websocket_unavailable_in_demo',
          message: 'WebSocket streaming requires the BOQA backend. Set BOQA_BACKEND_URL to enable real-time events.',
        }),
        { status: 426, headers: { 'Content-Type': 'application/json' } }
      );
    }

    // /health → quick Worker health check (no backend required)
    if (url.pathname === '/health') {
      return new Response(
        JSON.stringify({
          status: 'ok',
          worker: 'boqa',
          time: new Date().toISOString(),
          mode: backendConfigured ? 'production' : 'demo',
          backend_configured: backendConfigured,
          default_api_key: 'BOQA123',
        }),
        {
          status: 200,
          headers: { 'Content-Type': 'application/json' },
        }
      );
    }

    // Everything else → serve from static assets (dashboard)
    if (env && env.ASSETS) {
      // Add no-cache headers for HTML/JS/CSS so users always get the latest version
      const assetRes = await env.ASSETS.fetch(request);
      const url = new URL(request.url);
      const isHtml = url.pathname === '/' || url.pathname.endsWith('.html');
      const isJs = url.pathname.endsWith('.js');
      const isCss = url.pathname.endsWith('.css');
      if (isHtml || isJs || isCss) {
        const headers = new Headers(assetRes.headers);
        headers.set('Cache-Control', 'no-cache, no-store, must-revalidate');
        headers.set('Pragma', 'no-cache');
        headers.set('Expires', '0');
        return new Response(assetRes.body, {
          status: assetRes.status,
          statusText: assetRes.statusText,
          headers,
        });
      }
      return assetRes;
    }

    return new Response('BOQA Worker — no assets bound', { status: 404 });
  },
};
